# Base image
FROM node:16
RUN apt-get -y install fontconfig
# Install dependencies
RUN apt-get update && apt-get install -y \
  gconf-service \
  libasound2 \
  libatk1.0-0 \
  libc6 \
  libcairo2 \
  libcups2 \
  libdbus-1-3 \
  libexpat1 \
  libfontconfig1 \
  libgcc1 \
  libgconf-2-4 \
  libgdk-pixbuf2.0-0 \
  libglib2.0-0 \
  libgtk-3-0 \
  libnspr4 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libstdc++6 \
  libx11-6 \
  libx11-xcb1 \
  libxcb1 \
  libxcomposite1 \
  libxcursor1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxi6 \
  libxrandr2 \
  libxrender1 \
  libxss1 \
  libxtst6 \
  ca-certificates \
  fonts-liberation \
  fonts-noto-color-emoji \
  git \
  wget \
  && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Install Puppeteer, html-pdf, and PhantomJS
# RUN npm i puppeteer html-pdf phantomjs-prebuilt

# Set Puppeteer environment variables
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_NO_SANDBOX=true \
    PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox

# Download and install Chrome
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
    && apt-get update \
    && apt-get install -y google-chrome-stable

RUN rm -f /etc/localtime \
&& ln -sv /usr/share/zoneinfo/Asia/Dhaka /etc/localtime \
&& echo "Asia/Dhaka" > /etc/timezone


RUN mkdir -p /usr/share/fonts/truetype/SolaimanLipi_bengali
COPY /fonts/SolaimanLipi_22-02-2012.ttf  /usr/share/fonts/truetype/SolaimanLipi_bengali
COPY ./dejavu/*.ttf /usr/share/fonts/
COPY ./dejavu/*.ttf /usr/local/share/fonts/
# COPY ./fonts/*.ttf /usr/share/fonts/
# COPY ./fonts/*.ttf /usr/local/share/fonts/
# RUN apk add ttf-freefont

# Rebuild the font cache.
RUN fc-cache -fv
RUN fc-list

# Copy your app files into the container
COPY . .

RUN cp .env.staging.example .env

RUN npm install
ENV OPENSSL_CONF /etc/ssl

# Install Puppeteer, html-pdf, and PhantomJS
RUN npm i puppeteer@19.9.0 html-pdf phantomjs-prebuilt --save
EXPOSE 5010
# Start your app
CMD [ "node", "--max-old-space-size=4096", "server.js" ]