FROM node:14
#FROM node:14
#FROM node:14-slim
RUN apt-get -y install fontconfig
# Install dependencies
RUN apt-get update
RUN apt-get install -y fonts-liberation gconf-service libappindicator1 libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgbm-dev libgdk-pixbuf2.0-0 libgtk-3-0 libicu-dev libjpeg-dev libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libpng-dev libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 xdg-utils
WORKDIR /usr/src/app


# Set Puppeteer environment variables
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_NO_SANDBOX=true \
    PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
# Download and install Chrome
# RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
#     && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
#     && apt-get update \
#     && apt-get install -y google-chrome-stable

RUN apt-get update && apt-get install curl gnupg -y \
  && curl --location --silent https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
  && apt-get update \
  && apt-get install google-chrome-stable -y --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

RUN rm -f /etc/localtime \
&& ln -sv /usr/share/zoneinfo/Asia/Dhaka /etc/localtime \
&& echo "Asia/Dhaka" > /etc/timezone

# RUN apk --no-cache add ttf-freefont fontconfig

RUN mkdir -p /usr/share/fonts/truetype/SolaimanLipi_bengali
COPY /fonts/SolaimanLipi_22-02-2012.ttf  /usr/share/fonts/truetype/SolaimanLipi_bengali
COPY ./dejavu/*.ttf /usr/share/fonts/
COPY ./dejavu/*.ttf /usr/local/share/fonts/
# COPY ./fonts/*.ttf /usr/share/fonts/
# COPY ./fonts/*.ttf /usr/local/share/fonts/
# RUN apk add ttf-freefont

# Rebuild the font cache.
RUN fc-cache -fv
RUN fc-list
# Create app directory


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
#COPY package*.json ./

# Bundle app source
COPY . .

RUN cp .env.staging.example .env

RUN npm install

RUN export OPENSSL_CONF=/etc/ssl/


RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C / \
    && npm config set user 0 \
    && npm install -g phantomjs-prebuilt 
    
# If you are building your code for production
# RUN npm ci --only=production
# Install Puppeteer, html-pdf, and PhantomJS



ENV NODE_OPTIONS=--max_old_space_size=4000
EXPOSE 5010
CMD [ "node", "server.js" ]
