#FROM node:14
FROM node:16-alpine

RUN apk add fontconfig

RUN apk update #&& apk add --no-cache tzdata
RUN rm -f /etc/localtime \
&& ln -sv /usr/share/zoneinfo/Asia/Dhaka /etc/localtime \
&& echo "Asia/Dhaka" > /etc/timezone

# RUN apk --no-cache add ttf-freefont fontconfig

# RUN mkdir -p /usr/share/fonts/truetype/SolaimanLipi_bengali
# COPY /fonts/SolaimanLipi_22-02-2012.ttf  /usr/share/fonts/truetype/SolaimanLipi_bengali
COPY ./dejavu/*.ttf /usr/share/fonts/
COPY ./dejavu/*.ttf /usr/local/share/fonts/
# COPY ./fonts/*.ttf /usr/share/fonts/
# COPY ./fonts/*.ttf /usr/local/share/fonts/
# RUN apk add ttf-freefont

# Rebuild the font cache.
RUN fc-cache -fv
RUN fc-list
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
#COPY package*.json ./

# Bundle app source
COPY . .

RUN cp .env.dev.example .env

RUN npm install

RUN export OPENSSL_CONF=/etc/ssl/


RUN wget -qO- "https://github.com/dustinblackman/phantomized/releases/download/2.1.1a/dockerized-phantomjs.tar.gz" | tar xz -C / \
    && npm config set user 0 \
    && npm install -g phantomjs-prebuilt 
    
# If you are building your code for production
# RUN npm ci --only=production
ENV NODE_OPTIONS=--max_old_space_size=4000
EXPOSE 5010
CMD [ "node", "server.js" ]
