var Enum = require('enum');
const AllSopsIds = new Enum({
    'IMPORT_PERMIT': 181,
    'TRADE_LICENSE': 188,
    'TRADE_LICENSE_RENEW': 189,
    'COMMERCIAL_OPERATION': 187,
    'LAND_USE_PLAN': 191,
    'LOCAL_SALES_PERMIT': 190,
    'LOCAL_PURCHASE_PERMIT': 183,
    'SAMPLE_IMPORT_PERMIT': 182,
    'OCCUPANCY': 195,
    'TECHNICAL_KNOW_HOW_FEE': 199,
    'SAMPLE_EXPORT_PERMIT': 186,
    'ROYALTY_FEE': 200,
    'VISA_RECOMMENDATION': 197,
    'VISA_ASSISTANCE': 192,
    'PROJECT_CLEARANCE': 196,
    'EXPORT_PERMIT': 185,
    'WORK_PERMIT': 198
})

module.exports={AllSopsIds};