var Enum = require('enum');
const AllSopsIds = new Enum({
    'IMPORTPERMIT': 181,
    'TRADELICENSE': 188,
    'TRADELICENSERENEW': 189,
    'COMMERCIALOPERATION': 187,
    'LANDUSEPLAN': 191,
    'LOCALSALESPERMIT': 190,
    'LOCALPURCHASEPERMIT': 183,
    'SAMPLEIMPORTPERMIT': 182,
    'OCCUPANCY': 195,
    'TECHNICALKNOWHOWFEE': 199,
    'SAMPLEEXPORTPERMIT': 186,
    'ROYALTYFEE': 200,
    'VISARECOMMENDATION': 197,
    'VISAASSISTANCE': 192,
    'PROJECTCLEARANCE': 196,
    'EXPORTPERMIT': 185,
    'WORKPERMIT': 198
})

module.exports={AllSopsIds};