var Enum = require('enum');
const AllSopsCodes = new Enum({
    'IMPORT_PERMIT': "IMPORT_PERMIT",
    'TRADE_LICENSE': "TRADE_LICENSE",
    'TRADE_LICENSE_RENEW': "TRADE_LICENSE_RENEW",
    'COMMERCIAL_OPERATION': "COMMERCIAL_OPERATION",
    'LAND_USE_PLAN': "LAND_USE_PLAN",
    'LOCAL_SALES_PERMIT': "LOCAL_SALES_PERMIT",
    'LOCAL_PURCHASE_PERMIT': "LOCAL_PURCHASE_PERMIT",
    'SAMPLE_IMPORT_PERMIT': "SAMPLE_IMPORT_PERMIT",
    'OCCUPANCY': "OCCUPANCY",
    'TECHNICAL_KNOW_HOW_FEE': "TECHNICAL_KNOW_HOW_FEE",
    'SAMPLE_EXPORT_PERMIT': "SAMPLE_EXPORT_PERMIT",
    'ROYALTY_FEE': "ROYALTY_FEE",
    'VISA_RECOMMENDATION': "VISA_RECOMMENDATION",
    'VISA_ASSISTANCE': "VISA_ASSISTANCE",
    'PROJECT_CLEARANCE': "PROJECT_CLEARANCE",
    'EXPORT_PERMIT': "EXPORT_PERMIT",
    'WORK_PERMIT': "WORK_PERMIT",
    'PROJECT_REGISTRATION' : "PROJECT_CLEARANCE"//"PROJECT_REGISTRATION"
})

module.exports={AllSopsCodes};