variables:
  imageAppVersion: "0.0.6"
  replicaCount: 1

  imageRepository: devpentabd/beza-certificate-service-staging
  imagePullPolicy: IfNotPresent

  hostName: beza-certificate-service-staging.svc.cluster.beza
  serviceType: ClusterIP
  servicePort: 80
  #servicePort: 443
  serviceTargetPort: 5010
  #nodePort: 30208

  imagePullSecrets: regcred

resources:
  requests:
    memory: "300Mi"
    cpu: "150m"
  limits:
    memory: "500Mi"
    cpu: "300m"
