name: Oss Reusable Action
on:
  push:
    branches: [ dev ]
jobs:
  oss-reusable-action:
    uses: pentaglobalsltd/actions/.github/workflows/oss_reusable_action_dev.yaml@master
    secrets: inherit
    with:
      branch: "dev"                       # Pass the input branch
      environment: "dev"                  # Pass the environment (e.g., dev, prod)
      docker_image: "beza-certificate-service-dev"   # Docker image name
      dockerfile: "Dockerfile.dev"        # Dockerfile.dev to use
      product_name: "beza-certificate-service-dev"   # Product name for DefectDojo
      engagement_name: "beza-certificate-service-dev"